# Steps single example

# See https://github.com/toml-lang/toml/blob/master/examples/example-v0.4.0.toml

[variables]
usbMountPoint = "/media/usb"




# Use an array of tables for the steps; they will be executed in order.
[[step]]
name = "Announce first step"
action = "echo"
[step.details]
message = "This is the first step."

[[step]]
name = "Run simple command"
action = "run"
[step.details]
command = "ls"
arguments = "-la ${usbMountPoint}"
[step.details.on_success]
warn = "This is a warning"
[step.details.on_failure]
abort = "This is an abort message!"


# [[step]]
# name = "Run shell command"
# action = "shell"
# [step.details]
# message = "ls -la | sed 's|\\(d[a-zA-Z0-9\\-]\\{9\\}\\).*|\\1|g'"
# # Store stdout in an environment variable "directories"
# stdout = "directories"
# [step.details.on_success]
# warn = "This is a warning"
# [step.details.on_failure]
# abort = "This is an abort message!"

[[step]]
name = "Set an environment variable"
action = "setenv"
[step.details]
variable = "explicit"
value = "This is the 'explicit' environment variable's content."

[[step]]
name = "Echo the variable previously set"
action = "echo"
[step.details]
message = "directories: ${directories}"

[[step]]
name = "Announce last step"
action = "echo"
[step.details]
message = "This is the last step."
