# Steps single example

# See https://github.com/toml-lang/toml/blob/master/examples/example-v0.4.0.toml

[variables]
usbMountPoint = "/media/usb"




# Use an array of tables for the steps; they will be executed in order.
[[step]]
name = "Announce first step"
action = "echo"
[step.details]
message = "This is the first step (home: ${HOME})."

[[step]]
name = "Run simple command"
action = "run"
[step.details]
command = "ls"
arguments = "-la ${usbMountPoint}"
[step.details.on_success]
warn = "This is a warning"
[step.details.on_failure]
abort = "USB mount point does not exists!"


[[step]]
name = "Run shell command, with working pipes"
action = "shell"
[step.details]
command = "ls -la | sed 's|\\(d[a-zA-Z0-9\\-]\\{9\\}\\).*|\\1|g'"
# command = "ls -la | grep Cargo"
[step.details.on_success]
echo = "Success!"
[step.details.on_failure]
abort = "This is an abort message!"

[[step]]
name = "Run shell command and store in variable"
action = "shell"
[step.details]
command = "ls -la | grep Cargo"
# Store stdout in an environment variable "listing"
stdout = "listing"
[step.details.on_success]
echo = "listing: ${listing}"

[[step]]
name = "Echo the variable previously set (listing)"
action = "echo"
[step.details]
message = "listing: ${listing}"

[[step]]
name = "Set an environment variable"
action = "setenv"
[step.details]
variable = "explicit"
value = "This is the 'explicit' environment variable's content."

[[step]]
name = "Echo the variable previously set (explicit)"
action = "echo"
[step.details]
message = "explicit: ${explicit}"

[[step]]
name = "Announce last step"
action = "echo"
[step.details]
message = "This is the last step."
